apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: h8ydidgt6-go-gitops
  description: This is GitOps manifest for h8ydidgt6-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=h8ydidgt6-go
    backstage.io/kubernetes-id: h8ydidgt6-go 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: h8ydidgt6-go-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:h8ydidgt6-go
